project:
  type: book
  output-dir: docs
  
book:
  title: "0023diary"
  author: "Lunan Wei"
  date: "2024/3/11"
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    - week5.qmd
    - week6.qmd
    - week7.qmd
    - week8.qmd
    - week9.qmd
    - week10.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt


editor: visual

